"""Add created_at to teacher_profiles

Revision ID: fbabe7756d5f
Revises: 23cfc8972246
Create Date: 2025-11-15 23:38:45.238892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbabe7756d5f'
down_revision = '23cfc8972246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
